language: ruby
dist: xenial
group: edge
services:
- redis-server
env:
  global:
  - RACK_ENV=test
  - COVERAGE=1
before_install:
  - gem install rubygems-update -v 3.4.22
- gem install bundler
- source example.env
script:
- bundle exec rake
